# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "minimal"  # Consider a cleaner theme for professional/academic focus
title                    : "Healthcare with Responsible AI - [Your Name]"
title_separator          : "-"
name                     : &name "[Your Name]"
description              : &description "Exploring Responsible AI in Healthcare - Researcher & Advocate"
url                      : https://yourgithubusername.github.io
baseurl                  : "" 
repository               : "yourgithubusername/yourrepositoryname"

# Site Author - Customize author information to reflect healthcare & AI expertise
author:
  avatar           : "profile.png"
  name             : "[Your Name]"
  pronouns         : "he/him" # Customize if needed
  bio              : "Researcher in Healthcare AI | Responsible AI Advocate | Exploring AI ethics and its applications in medicine."
  location         : "Global (Remote & On-Site Collaborations)"
  employer         : "Independent Researcher / Healthcare Institution (optional)"
  uri              : "https://yourpersonalwebsite.com"  # Optional personal domain
  email            : "contact@yourdomain.com"  # Consider professional email

  # Academic websites - Highlight Google Scholar, ORCID, and PubMed for credibility
  arxiv            : 
  googlescholar    : "https://scholar.google.com/citations?user=YourGoogleScholarID"
  impactstory      : 
  orcid            : "https://orcid.org/YourORCIDID"
  semantic         : 
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=YourName"

  # Repositories and software development - Emphasize GitHub for open-source projects
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "yourgithubusername"
  kaggle           : "yourkaggleusername"  # If you do data science competitions or share healthcare datasets
  stackoverflow    : 

  # Social media - Focus on professional networks like LinkedIn
  bluesky          : 
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : "yourlinkedinusername"
  mastodon         : 
  medium           : "https://medium.com/@yourusername"  # If you write blogs on AI & healthcare
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 

# Additional desired changes:
# - Consider enabling Google Analytics if you want to track traffic
# - Add a blog section to write articles on responsible AI in healthcare
# - Customize sidebar to show a "Projects" section focused on Responsible AI tools or case studies

